"use client";

import { useMemo, useState } from "react";
import { useRouter } from "next/navigation";
import { ArrowRight, Check, ChevronDown, ChevronRight, Download, FileText, GitCompare, MessageSquareText, Printer, Quote, ShieldCheck, Sparkles, Trash2, Upload, X } from "lucide-react";
import { calculateTotals } from "@/domain/estimation";
import { sourceLocale, wordCount } from "@/domain/source";
import type { Citation, EstimateLine, Question, ScopeModule } from "@/domain/schemas";
import { formatDateFor, translate, useI18n } from "@/i18n";
import { resolvedClientLanguage } from "@/infrastructure/project-repository";
import { useWorkspace } from "./workspace-provider";

export function ProjectScreen({ step }: { step: string }) {
  if (step === "sources") return <SourcesScreen/>;
  if (step === "analysis") return <AnalysisScreen/>;
  if (step === "questions") return <QuestionsScreen/>;
  if (step === "estimate") return <EstimateScreen/>;
  if (step === "preview") return <PreviewScreen/>;
  return null;
}

function PageHeader({ eyebrow, title, copy, action }: { eyebrow: string; title: string; copy: string; action?: React.ReactNode }) {
  return <div className="page-head"><div><div className="eyebrow">{eyebrow}</div><h1>{title}</h1><p>{copy}</p></div>{action}</div>;
}

function AIStatus() {
  const { state, busy } = useWorkspace();
  const { t } = useI18n();
  if (!state.aiExecution && !busy) return null;
  const activeLabel = busy ? ({ analysis: t("assistant.consolidating"), questions: t("assistant.questions"), scope: t("assistant.scope"), estimate: t("assistant.estimate"), review: t("assistant.review") } as const)[busy] : undefined;
  return <div className="ai-strip" role="status" aria-live="polite"><span style={{ display: "flex", alignItems: "center", gap: 9 }}>{busy ? <span className="ai-progress-mark" aria-hidden="true"><i/><i/><i/></span> : <Sparkles size={17} color="#2f6b9a"/>}<strong>{activeLabel ?? (state.aiExecution?.mode === "openai" ? t("common.generatedWith", { model: state.aiExecution.model }) : t("common.demoFallback"))}</strong></span><span className="muted">{busy ? t("assistant.preserving") : t("common.structuredValidated")}</span></div>;
}

function ErrorBanner() { const { error } = useWorkspace(); const { t } = useI18n(); return error ? <div role="alert" className="error-banner"><strong>{t("errors.actionFailed")}</strong><span>{t("errors.preserved")}</span><details><summary>{t("errors.technical")}</summary><p>{error}</p></details></div> : null; }

function SourcesScreen() {
  const router = useRouter(); const { t } = useI18n(); const { state, busy, runAnalysis, updateSource, updateSourceLanguage, addSource, removeSource } = useWorkspace(); const [open, setOpen] = useState(state.sources[0]?.id);
  const analyze = async () => { await runAnalysis(); router.push(`/projects/${state.project.id}/analysis`); };
  const importFile = async (file?: File) => { if (!file) return; const extension = file.name.split(".").pop()?.toLowerCase(); const content = await file.text(); addSource(file.name.replace(/\.(md|txt)$/i, ""), content, extension === "md" ? "markdown" : "pasted_text"); };
  return <><PageHeader eyebrow={t("sources.eyebrow")} title={t("sources.title")} copy={t("sources.copy")} action={<div className="source-actions"><label className="btn"><Upload size={16}/>{t("sources.import")}<input type="file" accept=".md,.txt,text/markdown,text/plain" onChange={(event) => { void importFile(event.target.files?.[0]); event.currentTarget.value = ""; }}/></label><button className="btn btn-primary" disabled={!!busy || state.sources.length < 2 || state.sources.some((source) => !source.content.trim())} onClick={analyze}><Sparkles size={17}/>{busy ? t("sources.analyzing") : t("sources.analyze")}</button></div>}/><ErrorBanner/>
    <div className="card source-package"><div><strong>{t("sources.packageTitle", { name: state.project.name })}</strong><p className="muted">{t("sources.packageCopy")}</p></div><span className="badge badge-green"><ShieldCheck size={13}/>{t("common.fictionalData")}</span></div>
    <div style={{ display: "grid", gap: 14 }}>{state.sources.map((source, index) => <article className="card" key={source.id}>
      <div className="source-card-head"><button aria-expanded={open === source.id} onClick={() => setOpen(open === source.id ? "" : source.id)}><span className="source-icon"><FileText size={19}/></span><span><strong>{t("common.source")} {String.fromCharCode(65 + index)}: {source.title}</strong><small>{source.origin}, {wordCount(source.content)} {t("common.words")}, {source.paragraphs.length} {t("common.references")}</small></span><span className="source-language-badge">{source.language.isMultilingual ? t("common.mixed") : sourceLocale(source)?.toUpperCase() ?? "?"}</span>{open === source.id ? <ChevronDown/> : <ChevronRight/>}</button>{index > 2 && <button className="btn btn-ghost btn-sm source-remove" aria-label={t("sources.remove", { title: source.title })} onClick={() => removeSource(source.id)}><Trash2 size={15}/></button>}</div>
      {open === source.id && <div className="source-editor"><div className="source-language-control"><div><span className="eyebrow">{t("sources.detectedLanguage")}</span><strong>{source.language.isMultilingual ? t("sources.multilingual") : source.language.detectedLocale === "fr" ? t("common.french") : source.language.detectedLocale === "en" ? t("common.english") : t("common.unknown")}</strong><small>{source.language.confidence ? t("sources.languageMethod", { confidence: Math.round(source.language.confidence * 100) }) : t("sources.unknownLanguage")}</small></div><label><span>{t("sources.languageOverride")}</span><select value={source.language.userOverride ?? ""} onChange={(event) => updateSourceLanguage(source.id, event.target.value || null)}><option value="">{t("sources.useDetection")}</option><option value="fr">{t("common.french")}</option><option value="en">{t("common.english")}</option></select></label></div><label htmlFor={`source-${source.id}`} className="eyebrow">{t("sources.editableText")}</label><textarea id={`source-${source.id}`} value={source.content} onChange={(event) => updateSource(source.id, event.target.value)}/></div>}
    </article>)}</div>
  </>;
}

function CitationChips({ citations }: { citations: Citation[] }) {
  const { state, updateSourceLanguage } = useWorkspace(); const { t } = useI18n();
  const [active, setActive] = useState<Citation>();
  const source = state.sources.find((item) => item.id === active?.sourceId);
  return <><div className="citation-list">{citations.map((citation) => <button type="button" className="citation-chip" key={`${citation.sourceId}-${citation.paragraphId}`} onClick={() => setActive(citation)} aria-label={`${t("analysis.sourceEvidence")} ${citation.paragraphId}`}><Quote size={11}/>{citation.sourceId.replace("SRC-0", `${t("common.source")} `)}<span>{citation.paragraphId.split("-").at(-1)}</span>{citation.excerptLocale && <i>{citation.excerptLocale.toUpperCase()}</i>}</button>)}</div>
    {active && <div className="evidence-layer" role="dialog" aria-modal="true" aria-label={t("analysis.sourceEvidence")}><button className="evidence-backdrop" aria-label={t("common.close")} onClick={() => setActive(undefined)}/><aside className="evidence-drawer"><header><div><span className="eyebrow">{t("analysis.sourceEvidence")}</span><h2>{source?.title}</h2><p>{source?.origin}</p></div><button className="btn btn-ghost" aria-label={t("common.close")} onClick={() => setActive(undefined)}><X size={18}/></button></header>{source && <div className="drawer-language-control"><span className="badge badge-green">{source.language.isMultilingual ? t("common.mixed") : sourceLocale(source)?.toUpperCase() ?? "?"}</span><label>{t("sources.languageOverride")}<select value={source.language.userOverride ?? ""} onChange={(event) => updateSourceLanguage(source.id, event.target.value || null)}><option value="">{t("sources.useDetection")}</option><option value="fr">FR</option><option value="en">EN</option></select></label></div>}<div className="evidence-focus"><span className="badge badge-blue">{active.paragraphId} · {active.excerptLocale?.toUpperCase() ?? "?"}</span><small>{t("analysis.originalExcerpt")}</small><p>“{active.excerpt}”</p>{active.translatedExcerpt && <div className="translated-excerpt"><small>{t("analysis.translatedExcerpt")}</small><p>{active.translatedExcerpt}</p></div>}</div><div className="source-paragraphs">{source?.paragraphs.map((paragraph) => <section className={paragraph.id === active.paragraphId ? "highlighted" : ""} key={paragraph.id}><small>{paragraph.id}</small><p>{paragraph.text}</p></section>)}</div><footer><button className="btn" onClick={() => setActive(undefined)}>{t("analysis.backToConsolidated")}</button></footer></aside></div>}
  </>;
}

function AnalysisScreen() {
  const router = useRouter(); const { t, number } = useI18n(); const { state, busy, generateQuestions, runAnalysis } = useWorkspace(); const analysis = state.analysis; const [tab, setTab] = useState<"consolidated"|"contributions"|"open">("consolidated");
  if (!analysis) return <EmptyStep title={t("analysis.noAnalysis")} copy={t("analysis.noAnalysisCopy")} action={t("sources.analyze")} onClick={runAnalysis}/>;
  const generate = async () => { await generateQuestions(); router.push(`/projects/${state.project.id}/questions`); };
  const unknowns = analysis.findings.filter((finding) => finding.category === "unknown" || finding.category === "assumption");
  const categoryLabel = (category: string) => ({ goal: state.project.resolvedProjectLanguage === "fr" ? "objectif" : "goal", user: state.project.resolvedProjectLanguage === "fr" ? "utilisateur" : "user", requirement: state.project.resolvedProjectLanguage === "fr" ? "exigence" : "requirement", constraint: state.project.resolvedProjectLanguage === "fr" ? "contrainte" : "constraint", inclusion: state.project.resolvedProjectLanguage === "fr" ? "inclusion" : "inclusion", exclusion: state.project.resolvedProjectLanguage === "fr" ? "exclusion" : "exclusion", assumption: state.project.resolvedProjectLanguage === "fr" ? "hypothèse" : "assumption" } as Record<string,string>)[category] ?? category;
  return <><PageHeader eyebrow={t("analysis.eyebrow")} title={t("analysis.title")} copy={t("analysis.copy")} action={<button className="btn btn-primary" disabled={!!busy} onClick={generate}><MessageSquareText size={17}/>{t("analysis.generateQuestions")}</button>}/><AIStatus/><ErrorBanner/>
    <div className="card analysis-summary"><div><div className="mono">{number(analysis.coverageScore)}%</div><span className="muted">{t("analysis.coverage")}</span></div><div><strong>{t("analysis.summary")}</strong><p>{analysis.executiveSummary}</p>{state.analysisVersions.length > 0 && <span className="version-note">{t("analysis.version", { version: state.analysisVersions.length + 1 })} · {t("analysis.preservedVersion")}</span>}</div></div>
    <div className="analysis-tabs">{([ ["consolidated",t("analysis.consolidated")], ["contributions",t("analysis.contributions")], ["open",t("analysis.openPoints")] ] as const).map(([id,label]) => <button key={id} className={`btn btn-sm ${tab === id ? "btn-primary" : ""}`} onClick={() => setTab(id)}>{label}</button>)}</div>
    {tab === "consolidated" && <div className="finding-grid">{analysis.findings.filter((finding) => finding.category !== "unknown").map((finding) => { const sourceCount = new Set(finding.citations.map((citation) => citation.sourceId)).size; return <article className="card finding-card" key={finding.id}><div className="finding-meta"><span className="badge badge-muted">{categoryLabel(finding.category)}</span><span className="muted mono">{number(Math.round(finding.confidence * 100))}% {t("common.confidence")}</span></div><p>{finding.statement}</p><div className="confirmation-line"><span>{t(sourceCount === 1 ? "analysis.supporting" : "analysis.supportingPlural", { count: sourceCount })}</span></div><CitationChips citations={finding.citations}/></article>; })}</div>}
    {tab === "contributions" && <div className="contribution-list">{analysis.sourceContributions.map((item, index) => <article className="card contribution-card" style={{ animationDelay: `${index * 45}ms` }} key={item.id}><div><span className="badge badge-blue">{t("analysis.sourceLabel", { number: item.sourceId.replace(/\D/g, "") || index + 1 })}</span><span className={`relation relation-${item.relation}`}>{t(`analysis.${item.relation}`)}</span></div><div><strong>{item.topic}</strong><p>{item.contribution}</p><CitationChips citations={item.citations}/></div></article>)}</div>}
    {tab === "open" && <div className="open-points">{unknowns.map((finding) => <article className="card" key={finding.id}><span className="badge badge-amber">{t("analysis.needsClarification")}</span><p>{finding.statement}</p><CitationChips citations={finding.citations}/></article>)}{analysis.inconsistencies.length === 0 && <div className="consistency-note"><Check size={16}/><span><strong>{t("analysis.noInconsistencies")}</strong><small>{t("analysis.noInconsistenciesCopy")}</small></span></div>}</div>}
  </>;
}

function QuestionsScreen() {
  const router = useRouter(); const { t, date } = useI18n(); const { state, busy, generateQuestions, respond, setQuestionStatus, buildScope } = useWorkspace();
  const french = state.project.resolvedProjectLanguage === "fr";
  const [answers, setAnswers] = useState<Record<string,string>>({ "Q-01": french ? "Conserver les demandes refusées pendant douze mois, puis les anonymiser automatiquement." : "Keep wait-list promotion manual for launch. When an offer expires, notify the coordinator and release capacity only after their confirmation." });
  const [filter, setFilter] = useState<"all" | Question["priority"]>("all");
  if (!state.questions.length) return <EmptyStep title={t("questions.empty")} copy={t("questions.emptyCopy")} action={t("questions.generate")} onClick={generateQuestions}/>;
  const build = async () => { await buildScope(); router.push(`/projects/${state.project.id}/estimate`); };
  const answered = state.questions.filter((q) => q.status !== "open").length;
  const visible = filter === "all" ? state.questions : state.questions.filter((question) => question.priority === filter);
  const impact: Record<string, string[]> = french ? { "Q-01": ["Administration sécurisée"], "Q-02": ["Administration sécurisée"], "Q-03": ["Version anglaise"], "Q-04": ["Notifications e-mail"] } : { "Q-01": ["Review, offers & wait-list", "Email notifications"], "Q-02": ["Cohort operations"], "Q-03": ["French localization"], "Q-04": ["Email notifications"] };
  const priorityLabel = (item: string) => item === "all" ? t("common.all") : t(`common.${item}`);
  const statusLabel = (item: string) => item === "open" ? t("common.open") : item === "answered" ? t("common.recorded") : item === "deferred" ? t("common.deferred") : t("questions.notRelevant");
  return <><PageHeader eyebrow={t("questions.eyebrow")} title={t("questions.title")} copy={t("questions.copy")} action={<button className="btn btn-primary" disabled={!!busy || !state.decisions.length} onClick={build}>{t("questions.buildScope")}<ArrowRight size={17}/></button>}/><AIStatus/><ErrorBanner/>
    <div className="decision-toolbar card"><div><strong>{t("questions.handled", { done: answered, total: state.questions.length })}</strong><span>{t("questions.blockingRemain", { count: state.questions.filter((q) => q.priority === "blocking" && q.status === "open").length })}</span></div><div className="progress-track"><i style={{ width: `${answered / state.questions.length * 100}%` }}/></div><div className="filter-group" aria-label={t("questions.filter")}>{(["all", "blocking", "framing", "optional"] as const).map((item) => <button aria-pressed={filter === item} className={`btn btn-sm ${filter === item ? "btn-primary" : ""}`} key={item} onClick={() => setFilter(item)}>{priorityLabel(item)}</button>)}</div></div>
    <div className="question-list">{visible.map((question) => <article className={`card question-card priority-${question.priority} ${question.status !== "open" ? "resolved" : ""}`} key={question.id}>
      <div style={{ display: "flex", justifyContent: "space-between", gap: 12 }}><span className={`badge ${question.priority === "blocking" ? "badge-red" : question.priority === "framing" ? "badge-amber" : "badge-blue"}`}>{priorityLabel(question.priority)}</span><span className="badge badge-muted">{statusLabel(question.status)}</span></div><h2 style={{ fontSize: 19, margin: "14px 0 7px" }}>{question.text}</h2><p className="muted" style={{ margin: "0 0 6px", fontSize: 14 }}>{question.rationale}</p><p style={{ margin: 0, fontSize: 13 }}><strong>{t("questions.estimateImpact")}</strong> {question.estimationImpact}</p><CitationChips citations={question.citations}/>
      <div className="impact-preview"><span>{t("questions.potentialImpact")}</span>{impact[question.id]?.map((module) => <span className="badge badge-muted" key={module}>{module}</span>)}</div>
      {question.status === "open" && <div className="answer-panel"><div className="quick-answers"><span>{t("questions.quickAnswers")}</span><button onClick={() => setAnswers({ ...answers, [question.id]: french ? "Conserver ce traitement manuel au lancement et tracer chaque action." : "Keep this manual for launch and record the action in the audit history." })}>{t("questions.manualLaunch")}</button><button onClick={() => setAnswers({ ...answers, [question.id]: french ? "Inclure le workflow automatisé dans le périmètre initial." : "Include the automated workflow in the initial release." })}>{t("questions.includeLaunch")}</button><button onClick={() => setAnswers({ ...answers, [question.id]: french ? "Déplacer cette capacité dans une option chiffrée séparément." : "Move this capability to a separately priced option." })}>{t("questions.moveOptions")}</button></div><label htmlFor={`answer-${question.id}`}>{t("questions.decisionAnswer")}</label><textarea id={`answer-${question.id}`} rows={3} value={answers[question.id] ?? ""} onChange={(event) => setAnswers({ ...answers, [question.id]: event.target.value })}/><div className="answer-actions"><button className="btn btn-success btn-sm" disabled={!answers[question.id]?.trim()} onClick={() => respond(question.id, answers[question.id] ?? "")}><Check size={14}/>{t("questions.recordDecision")}</button><button className="btn btn-sm" onClick={() => setQuestionStatus(question.id, "deferred")}>{t("questions.defer")}</button><button className="btn btn-ghost btn-sm" onClick={() => setQuestionStatus(question.id, "ignored")}>{t("questions.notRelevant")}</button></div></div>}
      {question.answer && <div className="recorded-decision"><Check size={17}/><div><strong>{t("decisions.recorded")}</strong><p>{question.answer}</p><small>{t("questions.scopeImpactCopy")}</small></div></div>}
    </article>)}</div>
    {state.decisions.length > 0 && <section className="card decision-history"><div><span className="eyebrow">{t("decisions.history")}</span><h2>{t(state.decisions.length === 1 ? "decisions.traceable" : "decisions.traceablePlural", { count: state.decisions.length })}</h2></div>{state.decisions.slice().reverse().map((decision) => <div className="history-row" key={decision.id}><span className="badge badge-green">{t("common.recorded")}</span><p>{decision.statement}</p><time>{date(decision.createdAt, { timeStyle: "short" })}</time></div>)}</section>}
  </>;
}

function EmptyStep({ title, copy, action, onClick }: { title: string; copy: string; action: string; onClick: () => void | Promise<void> }) {
  return <div className="card empty-step"><span className="empty-step-icon"><Sparkles size={26}/></span><h1>{title}</h1><p className="muted">{copy}</p><button className="btn btn-primary" onClick={onClick}>{action}</button></div>;
}

function EstimateScreen() {
  const router = useRouter(); const { t } = useI18n(); const { state, busy, buildScope, generateEstimate, changeModuleStatus, editEstimate, setContingency, reviewLine, editProposalAfter, resolveProposal } = useWorkspace();
  const [selectedId, setSelectedId] = useState<string>();
  const [search, setSearch] = useState("");
  const [statusFilter, setStatusFilter] = useState<"all" | ScopeModule["status"]>("all");
  const [collapsed, setCollapsed] = useState<Set<string>>(new Set());
  const [assistantInsight, setAssistantInsight] = useState<string>();
  const [editingProposal, setEditingProposal] = useState(false);
  if (!state.workstreams.length) return <EmptyStep title={t("scope.empty")} copy={t("scope.emptyCopy")} action={t("scope.build")} onClick={buildScope}/>;
  if (!state.estimateLines.length) return <><PageHeader eyebrow={t("scope.eyebrow")} title={t("scope.title")} copy={t("scope.copy")} action={<button className="btn btn-primary" disabled={!!busy} onClick={generateEstimate}><Sparkles size={17}/>{t("scope.generateEstimate")}</button>}/><ScopeCards workstreams={state.workstreams} changeStatus={changeModuleStatus}/></>;
  const modules = state.workstreams.flatMap((w) => w.modules); const moduleMap = new Map(modules.map((m) => [m.id, m])); const totals = calculateTotals(state.estimateLines, modules, state.project.contingencyRate, state.project.preferences); const selected = state.estimateLines.find((line) => line.id === selectedId) ?? state.estimateLines.find((line) => moduleMap.get(line.moduleId)?.status === "included"); const proposal = state.changeProposal?.status === "pending" ? state.changeProposal : undefined;
  const visibleWorkstreams = state.workstreams.map((workstream) => ({ ...workstream, modules: workstream.modules.filter((module) => (statusFilter === "all" || module.status === statusFilter) && `${module.name} ${module.description} ${module.features.join(" ")}`.toLowerCase().includes(search.toLowerCase())) })).filter((workstream) => workstream.modules.length);
  const selectedModule = selected ? moduleMap.get(selected.moduleId) : undefined;
  const statusLabel = (item: string) => item === "all" ? t("common.all") : t(`common.${item}`);
  return <><PageHeader eyebrow={t("estimate.eyebrow")} title={t("estimate.title")} copy={t("estimate.copy")} action={<button className="btn" onClick={() => router.push(`/projects/${state.project.id}/preview`)}>{t("estimate.preview")}<ArrowRight size={17}/></button>}/><AIStatus/><ErrorBanner/>
    <div className="estimate-toolbar card"><label><span>{t("estimate.search")}</span><input type="search" placeholder={t("estimate.searchPlaceholder")} value={search} onChange={(event) => setSearch(event.target.value)}/></label><div className="filter-group" aria-label={t("estimate.filter")}>{(["all", "included", "optional", "excluded", "deferred"] as const).map((item) => <button className={`btn btn-sm ${statusFilter === item ? "btn-primary" : ""}`} aria-pressed={statusFilter === item} key={item} onClick={() => setStatusFilter(item)}>{statusLabel(item)}</button>)}</div><div className="estimate-count"><strong>{modules.length}</strong><span>{t("common.modules")}</span></div></div>
    <div className="estimate-layout"><div className="card estimate-table-wrap"><table className="estimate-table"><thead><tr>{[t("common.modules"),t("common.status"),t("common.low"),t("common.likely"),t("common.high"),t("common.risk"),""].map((h) => <th key={h}>{h}</th>)}</tr></thead><tbody>{visibleWorkstreams.map((ws) => <TableWorkstream key={ws.id} workstream={ws} lines={state.estimateLines} selectedId={selected?.id} select={(id) => { setSelectedId(id); setAssistantInsight(undefined); }} changeStatus={changeModuleStatus} edit={editEstimate} collapsed={collapsed.has(ws.id)} toggle={() => setCollapsed((current) => { const next = new Set(current); if (next.has(ws.id)) next.delete(ws.id); else next.add(ws.id); return next; })}/>)}</tbody></table>{!visibleWorkstreams.length && <div className="table-empty">{t("estimate.noMatches")}</div>}</div>
    <aside className="card copilot-panel"><div className="copilot-title"><span className="eyebrow">{t("estimate.contextualCopilot")}</span><span className="badge badge-muted">{t("estimate.humanControlled")}</span></div>{selected ? <><h2>{selectedModule?.name}</h2><div className="line-signals"><span className={`badge badge-${selected.risk === "high" ? "red" : selected.risk === "medium" ? "amber" : "green"}`}>{t(`common.${selected.risk}`)} {t("common.risk")}</span><span className="badge badge-muted">{t(`common.${selected.confidence}`)} {t("common.confidence")}</span>{selected.manualOverride && <span className="badge badge-blue">{t("common.manualOverride")}</span>}</div><CitationChips citations={selectedModule?.citations ?? []}/><p className="copilot-rationale">{selected.rationale}</p><div className="copilot-actions"><button onClick={() => setAssistantInsight(`${t("assistant.explanationPrefix", { features: selectedModule?.features.join(", ") ?? "" })} ${selected.rationale}`)}>{t("estimate.explain")}</button><button onClick={() => setAssistantInsight(`${selectedModule?.dependencies.length ? `${selectedModule.dependencies.join(", ")}. ` : t("assistant.noDependency")}${selectedModule?.assumptions.join(" ") || t("assistant.noAssumption")}`)}>{t("estimate.missingWork")}</button><button onClick={() => setAssistantInsight(t("assistant.evidenceCount", { count: selectedModule?.citations.length ?? 0 }))}>{t("estimate.compareEvidence")}</button><button onClick={() => setAssistantInsight(t("assistant.clientWording", { text: selectedModule?.description ?? "" }))}>{t("estimate.rewriteClient")}</button></div>{assistantInsight && <div className="workspace-insight"><span>{t("estimate.workspaceInsight")}</span><p>{assistantInsight}</p></div>}<button className="btn btn-primary challenge-button" disabled={!!busy} onClick={() => reviewLine(selected)}><GitCompare size={16}/>{t("estimate.challenge")}</button></> : <p className="muted">{t("estimate.selectLine")}</p>}
      {proposal && <div className="proposal-diff"><div className="diff-heading"><span className="badge badge-blue">{t("estimate.aiProposal")}</span><small>{t("estimate.noSilentChange")}</small></div><p>{proposal.explanation}</p><Diff before={proposal.before} after={proposal.after}/>{editingProposal && <div className="proposal-edit"><span>{t("estimate.adjustRange")}</span>{(["low", "likely", "high"] as const).map((key) => <label key={key}>{t(`common.${key}`)}<input aria-label={t(`estimate.proposed${key[0].toUpperCase()}${key.slice(1)}`)} type="number" min="0" step="0.5" value={proposal.after[key]} onChange={(event) => editProposalAfter({ [key]: Number(event.target.value) })}/></label>)}</div>}<div className="diff-actions"><button className="btn btn-success btn-sm" onClick={() => resolveProposal(true)}><Check size={14}/>{t("common.accept")}</button><button className="btn btn-sm" aria-pressed={editingProposal} onClick={() => setEditingProposal((value) => !value)}>{t("common.modify")}</button><button className="btn btn-danger btn-sm" onClick={() => resolveProposal(false)}><X size={14}/>{t("common.reject")}</button></div></div>}
    </aside></div>
    <div className="totals-dock card mono"><Total label={t("estimate.baseLow")} value={totals.base.low}/><Total label={t("estimate.baseLikely")} value={totals.base.likely}/><Total label={t("estimate.baseHigh")} value={totals.base.high}/><label>{t("common.reserve")}<select aria-label={t("estimate.estimateReserve")} value={state.project.contingencyRate} onChange={(e) => setContingency(Number(e.target.value))}><option value={0.1}>10%</option><option value={0.15}>15%</option><option value={0.2}>20%</option></select></label><Total label={t("estimate.proposedLikelyTotal")} value={totals.proposed.likely} accent/><div className="option-total"><span>{t("common.options")}</span><strong>{totals.options.low} / {totals.options.likely} / {totals.options.high} {state.project.estimationUnit === "day" ? t("common.dayShort") : t("common.hourShort")}</strong></div></div>
  </>;
}

function ScopeCards({ workstreams, changeStatus }: { workstreams: ReturnType<typeof useWorkspace>["state"]["workstreams"]; changeStatus: ReturnType<typeof useWorkspace>["changeModuleStatus"] }) { const { t } = useI18n(); return <div className="scope-grid">{workstreams.map((ws) => <section className="card scope-workstream" key={ws.id}><span className="eyebrow">{t("common.workstream")}</span><h2>{ws.name}</h2><p className="muted">{ws.description}</p><div className="scope-module-list">{ws.modules.map((module) => <div className="scope-module" key={module.id}><div><strong>{module.name}</strong><p className="muted">{module.features.join(", ")}</p><CitationChips citations={module.citations}/></div><StatusSelect value={module.status} onChange={(value) => changeStatus(module.id, value)}/></div>)}</div></section>)}</div>; }

function TableWorkstream({ workstream, lines, selectedId, select, changeStatus, edit, collapsed, toggle }: { workstream: ReturnType<typeof useWorkspace>["state"]["workstreams"][number]; lines: EstimateLine[]; selectedId?: string; select: (id: string) => void; changeStatus: ReturnType<typeof useWorkspace>["changeModuleStatus"]; edit: ReturnType<typeof useWorkspace>["editEstimate"]; collapsed: boolean; toggle: () => void }) { const { t } = useI18n(); return <><tr className="workstream-row"><th colSpan={7}><button type="button" aria-expanded={!collapsed} onClick={toggle}>{collapsed ? <ChevronRight size={16}/> : <ChevronDown size={16}/>}<span>{workstream.name}</span><small>{workstream.modules.length} {t("common.modules")}</small></button></th></tr>{!collapsed && workstream.modules.map((module) => { const line = lines.find((item) => item.moduleId === module.id); if (!line) return null; return <tr key={module.id} className={selectedId === line.id ? "selected" : ""} onClick={() => select(line.id)}><td><strong>{module.name}</strong>{line.manualOverride && <span className="edited-mark" title={t("common.manualOverride")}>{t("estimate.edited")}</span>}<small>{module.description}</small></td><td><StatusSelect value={module.status} onChange={(value) => changeStatus(module.id, value)}/></td>{(["low","likely","high"] as const).map((key) => <td key={key}><input aria-label={`${module.name} ${t(`common.${key}`)}`} type="number" min="0" step="0.5" value={line[key]} onClick={(event) => event.stopPropagation()} onChange={(event) => edit(line.id, { [key]: Number(event.target.value) })}/></td>)}<td><span className={`badge ${line.risk === "high" ? "badge-red" : line.risk === "medium" ? "badge-amber" : "badge-green"}`}>{t(`common.${line.risk}`)}</span></td><td><button className="btn btn-ghost btn-sm" aria-label={t("estimate.review", { name: module.name })} onClick={(event) => { event.stopPropagation(); select(line.id); }}><ChevronRight size={15}/></button></td></tr>; })}</>; }

function StatusSelect({ value, onChange }: { value: ScopeModule["status"]; onChange: (value: ScopeModule["status"]) => void }) { const { t } = useI18n(); return <select aria-label={t("common.status")} className={`status-select status-${value}`} value={value} onClick={(e) => e.stopPropagation()} onChange={(e) => onChange(e.target.value as ScopeModule["status"])}><option value="included">{t("common.included")}</option><option value="optional">{t("common.optional")}</option><option value="excluded">{t("common.excluded")}</option><option value="deferred">{t("common.deferred")}</option></select>; }
function Diff({ before, after }: { before: EstimateLine; after: EstimateLine }) { const { t } = useI18n(); const { state } = useWorkspace(); const unit = state.project.estimationUnit === "day" ? t("common.dayShort") : t("common.hourShort"); return <div className="diff-grid mono"><div className="diff-before"><span>{t("common.before")}</span><strong>{before.low} / {before.likely} / {before.high} {unit}</strong><small>{before.rationale}</small></div><div className="diff-after"><span>{t("common.after")}</span><strong>{after.low} / {after.likely} / {after.high} {unit}</strong><small>{after.rationale}</small></div></div>; }
function Total({ label, value, accent }: { label: string; value: number; accent?: boolean }) { const { t, number } = useI18n(); const { state } = useWorkspace(); return <div className={`total ${accent ? "accent" : ""}`}><span>{label}</span><strong>{number(value, { minimumFractionDigits: 1, maximumFractionDigits: 1 })} {state.project.estimationUnit === "day" ? t("common.dayShort") : t("common.hourShort")}</strong></div>; }

function PreviewScreen() {
  const { state, recordExport } = useWorkspace(); const { t } = useI18n(); const [mode, setMode] = useState<"internal"|"client">("client"); const modules = state.workstreams.flatMap((w) => w.modules); const totals = useMemo(() => calculateTotals(state.estimateLines, modules, state.project.contingencyRate, state.project.preferences), [state.estimateLines, modules, state.project.contingencyRate, state.project.preferences]);
  if (!state.estimateLines.length) return <EmptyStep title={t("preview.noProposal")} copy={t("preview.noProposalCopy")} action={t("preview.goScope")} onClick={() => location.assign(`/projects/${state.project.id}/estimate`)}/>;
  const optional = modules.filter((module) => module.status === "optional");
  const excluded = modules.filter((module) => module.status === "excluded");
  const clientLocale = resolvedClientLanguage(state); const pt = (key: string, values?: Record<string,string|number>) => mode === "client" ? translate(clientLocale, key, values) : t(key, values); const unit = state.project.estimationUnit === "day" ? pt("common.days") : pt("common.hours");
  const exportCsv = () => { const escape = (value: string | number | boolean) => `"${String(value).replaceAll('"', '""')}"`; const header = [translate(clientLocale, "common.workstream"), translate(clientLocale, "common.modules"), translate(clientLocale, "common.status"), translate(clientLocale, "common.low"), translate(clientLocale, "common.likely"), translate(clientLocale, "common.high"), translate(clientLocale, "common.risk"), translate(clientLocale, "common.confidence"), translate(clientLocale, "common.manualOverride"), clientLocale === "fr" ? "Références source" : "Source references"]; const rows = state.workstreams.flatMap((workstream) => workstream.modules.map((module) => { const line = state.estimateLines.find((item) => item.moduleId === module.id); return [workstream.name, module.name, translate(clientLocale, `common.${module.status}`), line?.low ?? 0, line?.likely ?? 0, line?.high ?? 0, line?.risk ? translate(clientLocale, `common.${line.risk}`) : "", line?.confidence ? translate(clientLocale, `common.${line.confidence}`) : "", line?.manualOverride ?? false, module.citations.map((citation) => citation.paragraphId).join(" | ")]; })); const blob = new Blob(["\ufeff", [header, ...rows].map((row) => row.map(escape).join(",")).join("\n")], { type: "text/csv;charset=utf-8" }); const url = URL.createObjectURL(blob); const link = document.createElement("a"); link.href = url; link.download = `scopeforge-${state.project.id}-${clientLocale}.csv`; link.click(); URL.revokeObjectURL(url); recordExport("CSV"); };
  const assumptions = state.project.resolvedProjectLanguage === "fr" ? ["Les contenus arrivent progressivement.", "Les attributions restent contrôlées au lancement.", "Les droits d’export sensibles sont confirmés au cadrage."] : ["Client content and photography arrive progressively.", "Wait-list promotion remains manual for launch.", "Refund decisions remain an operations process."];
  return <><PageHeader eyebrow={t("preview.eyebrow")} title={t("preview.title")} copy={t("preview.copy")} action={<div className="preview-actions no-print"><div className="view-switch" aria-label={t("preview.viewLabel")}><button aria-pressed={mode === "internal"} onClick={() => setMode("internal")}>{t("common.internal")}</button><button aria-pressed={mode === "client"} onClick={() => setMode("client")}>{t("common.clientReady")}</button><i className={mode}/></div>{mode === "internal" && <button className="btn" onClick={exportCsv}><Download size={16}/>{t("preview.estimateCsv")}</button>}<button className="btn" onClick={() => { recordExport("PDF"); window.print(); }}><Printer size={16}/>{t("preview.printPdf")}</button></div>}/>
    <div className={`view-safety no-print ${mode}`}><ShieldCheck size={16}/><span>{mode === "client" ? t("preview.clientSafe") : t("preview.internalSafe")}</span><small>{t("exports.clientLanguage", { language: clientLocale.toUpperCase() })}</small></div>
    <article lang={mode === "client" ? clientLocale : undefined} className={`card proposal-document proposal-${mode}`}><header className="proposal-cover"><div><div className="eyebrow">{pt("preview.proposalLabel")}</div><h1>{state.project.name}</h1><p>{pt("preview.prepared", { date: formatDateFor(mode === "client" ? clientLocale : "en", new Date(), { dateStyle: "medium" }) })}</p></div><span className="brand-signal proposal-brand" aria-label="ScopeForge"><i/><i/><i/><i/></span></header>
      <section className="proposal-intro"><span className="proposal-section-number">01</span><div><h2>{pt("preview.contextObjectives")}</h2><p>{state.analysis?.executiveSummary}</p><div className="objective-grid"><div><strong>{pt("preview.outcome")}</strong><span>{pt("preview.outcomeCopy")}</span></div><div><strong>{pt("preview.launchShape")}</strong><span>{pt("preview.launchShapeCopy")}</span></div><div><strong>{pt("preview.operatingModel")}</strong><span>{pt("preview.operatingModelCopy")}</span></div></div></div></section>
      <section className="proposal-scope"><span className="proposal-section-number">02</span><div><h2>{pt("preview.includedScope")}</h2>{state.workstreams.map((workstream) => <div className="proposal-workstream" key={workstream.id}><h3>{workstream.name}</h3>{workstream.modules.filter((module) => module.status === "included").map((module) => { const line = state.estimateLines.find((item) => item.moduleId === module.id); return <div className="proposal-module" key={module.id}><div><strong>{module.name}</strong><p>{module.description}</p>{mode === "internal" && <div className="internal-signals"><span className={`badge badge-${line?.risk === "high" ? "red" : line?.risk === "medium" ? "amber" : "green"}`}>{line?.risk && t(`common.${line.risk}`)} {t("common.risk")}</span><span className="badge badge-muted">{line?.confidence && t(`common.${line.confidence}`)} {t("common.confidence")}</span><CitationChips citations={module.citations}/></div>}</div>{(mode === "internal" || state.project.preferences.showEffortInClient) && <span className="mono">{line?.low}-{line?.high} {unit}</span>}</div>})}</div>)}</div></section>
      {(mode === "internal" || state.project.preferences.showEffortInClient) ? <section className="proposal-effort"><span><small>{pt("preview.effort")}</small><strong className="mono">{totals.proposed.low.toFixed(1)}-{totals.proposed.high.toFixed(1)} {unit}</strong></span><span><small>{pt("preview.planningCase")}</small><strong className="mono">{totals.proposed.likely.toFixed(1)} {unit}</strong></span><span><small>{pt("preview.calendar")}</small><strong>10-14 {pt("preview.weeks")}</strong></span>{mode === "internal" && <div className="internal-math">Base {totals.base.likely} + {t("common.reserve").toLowerCase()} {totals.reserve.likely} ({state.project.contingencyRate * 100}%)</div>}</section> : <div className="client-effort-hidden">{pt("preview.clientEffortHidden")}</div>}
      <section className="proposal-columns"><div><span className="proposal-section-number">03</span><h2>{pt("common.options")}</h2>{optional.map((module) => { const line = state.estimateLines.find((item) => item.moduleId === module.id); return <div className="proposal-option" key={module.id}><strong>{module.name}</strong>{(mode === "internal" || state.project.preferences.showEffortInClient) && <span className="mono">{line?.low}-{line?.high} {unit}</span>}<p>{module.description}</p></div>})}</div><div><span className="proposal-section-number">04</span><h2>{pt("preview.exclusions")}</h2><ul>{excluded.map((module) => <li key={module.id}>{module.name}</li>)}</ul><h2>{pt("preview.assumptions")}</h2><ul>{assumptions.map((assumption) => <li key={assumption}>{assumption}</li>)}</ul></div></section>
      {mode === "internal" && <section className="internal-appendix"><div><span className="proposal-section-number">05</span><h2>{t("preview.internalRecord")}</h2></div>{state.decisions.map((decision) => <div key={decision.id}><span className="badge badge-green">{t("common.recorded")}</span><p>{decision.statement}</p></div>)}<h3>{t("preview.recentActivity")}</h3>{state.activity.slice(-4).reverse().map((item) => <p className="activity-line" key={item.id}>{item.label}<time>{formatDateFor("en", item.createdAt, { timeStyle: "short" })}</time></p>)}</section>}
      <footer>{pt("preview.footer")}</footer>
    </article>
  </>;
}
