"use client";

import { useMemo, useState } from "react";
import { useRouter } from "next/navigation";
import { ArrowRight, Check, ChevronDown, ChevronRight, Download, FileText, GitCompare, MessageSquareText, Printer, Quote, ShieldCheck, Sparkles, Trash2, Upload, X } from "lucide-react";
import { calculateTotals } from "@/domain/estimation";
import { wordCount } from "@/domain/source";
import type { Citation, EstimateLine, Question, ScopeModule } from "@/domain/schemas";
import { useWorkspace } from "./workspace-provider";

export function ProjectScreen({ step }: { step: string }) {
  if (step === "sources") return <SourcesScreen/>;
  if (step === "analysis") return <AnalysisScreen/>;
  if (step === "questions") return <QuestionsScreen/>;
  if (step === "estimate") return <EstimateScreen/>;
  if (step === "preview") return <PreviewScreen/>;
  return null;
}

function PageHeader({ eyebrow, title, copy, action }: { eyebrow: string; title: string; copy: string; action?: React.ReactNode }) {
  return <div className="page-head"><div><div className="eyebrow">{eyebrow}</div><h1>{title}</h1><p>{copy}</p></div>{action}</div>;
}

function AIStatus() {
  const { state, busy } = useWorkspace();
  if (!state.aiExecution && !busy) return null;
  const activeLabel = busy ? ({ analysis: "Consolidating source evidence…", questions: "Finding material clarification points…", scope: "Reconciling decisions into scope…", estimate: "Proposing effort ranges…", review: "Reviewing the selected estimate line…" } as const)[busy] : undefined;
  return <div className="ai-strip" role="status" aria-live="polite"><span style={{ display: "flex", alignItems: "center", gap: 9 }}>{busy ? <span className="ai-progress-mark" aria-hidden="true"><i/><i/><i/></span> : <Sparkles size={17} color="#2f6b9a"/>}<strong>{activeLabel ?? (state.aiExecution?.mode === "openai" ? `Generated with ${state.aiExecution.model}` : "Demo fallback · precomputed output")}</strong></span><span className="muted">{busy ? "Preserving citations and validating the structured result" : "Structured output validated with Zod"}</span></div>;
}

function ErrorBanner() { const { error } = useWorkspace(); return error ? <div role="alert" className="error-banner"><strong>That action could not be completed.</strong><span>Your data is preserved. Review the detail, then retry when ready.</span><details><summary>Technical detail</summary><p>{error}</p></details></div> : null; }

function SourcesScreen() {
  const router = useRouter(); const { state, busy, runAnalysis, updateSource, addSource, removeSource } = useWorkspace(); const [open, setOpen] = useState(state.sources[0]?.id);
  const analyze = async () => { await runAnalysis(); router.push("/projects/demo/analysis"); };
  const importFile = async (file?: File) => { if (!file) return; const extension = file.name.split(".").pop()?.toLowerCase(); const content = await file.text(); addSource(file.name.replace(/\.(md|txt)$/i, ""), content, extension === "md" ? "markdown" : "pasted_text"); };
  return <><PageHeader eyebrow="Step 1 · Project evidence" title="Complementary sources, one traceable record" copy="Inspect or edit the fictional inputs before analysis. Documents are treated as untrusted evidence, never as model instructions." action={<div className="source-actions"><label className="btn"><Upload size={16}/> Import .md or .txt<input type="file" accept=".md,.txt,text/markdown,text/plain" onChange={(event) => { void importFile(event.target.files?.[0]); event.currentTarget.value = ""; }}/></label><button className="btn btn-primary" disabled={!!busy || state.sources.length < 2 || state.sources.some((source) => !source.content.trim())} onClick={analyze}><Sparkles size={17}/>{busy ? "Analyzing sources…" : "Analyze sources"}</button></div>}/><ErrorBanner/>
    <div className="card source-package"><div><strong>Morrow Ridge evidence package</strong><p className="muted">Three fictional sources that introduce, complement, confirm and refine the scope.</p></div><span className="badge badge-green"><ShieldCheck size={13}/> Fictional data</span></div>
    <div style={{ display: "grid", gap: 14 }}>{state.sources.map((source, index) => <article className="card" key={source.id}>
      <div className="source-card-head"><button aria-expanded={open === source.id} onClick={() => setOpen(open === source.id ? "" : source.id)}><span className="source-icon"><FileText size={19}/></span><span><strong>Source {String.fromCharCode(65 + index)}: {source.title}</strong><small>{source.origin}, {wordCount(source.content)} words, {source.paragraphs.length} stable references</small></span>{open === source.id ? <ChevronDown/> : <ChevronRight/>}</button>{index > 2 && <button className="btn btn-ghost btn-sm source-remove" aria-label={`Remove ${source.title}`} onClick={() => removeSource(source.id)}><Trash2 size={15}/></button>}</div>
      {open === source.id && <div style={{ padding: "0 18px 18px" }}><label htmlFor={`source-${source.id}`} className="eyebrow" style={{ display: "block", marginBottom: 8 }}>Editable source text</label><textarea id={`source-${source.id}`} value={source.content} onChange={(event) => updateSource(source.id, event.target.value)} style={{ width: "100%", minHeight: 270, resize: "vertical", padding: 15, color: "var(--text)", border: "1px solid var(--border)", borderRadius: 8, lineHeight: 1.55, background: "#fbfcfd" }}/></div>}
    </article>)}</div>
  </>;
}

function CitationChips({ citations }: { citations: Citation[] }) {
  const { state } = useWorkspace();
  const [active, setActive] = useState<Citation>();
  const source = state.sources.find((item) => item.id === active?.sourceId);
  return <><div className="citation-list">{citations.map((citation) => <button type="button" className="citation-chip" key={`${citation.sourceId}-${citation.paragraphId}`} onClick={() => setActive(citation)} aria-label={`Open ${citation.paragraphId} in source`}><Quote size={11}/>{citation.sourceId.replace("SRC-0", "Source ")}<span>{citation.paragraphId.split("-").at(-1)}</span></button>)}</div>
    {active && <div className="evidence-layer" role="dialog" aria-modal="true" aria-label="Source evidence"><button className="evidence-backdrop" aria-label="Close source evidence" onClick={() => setActive(undefined)}/><aside className="evidence-drawer"><header><div><span className="eyebrow">Source evidence</span><h2>{source?.title}</h2><p>{source?.origin}</p></div><button className="btn btn-ghost" aria-label="Close source evidence" onClick={() => setActive(undefined)}><X size={18}/></button></header><div className="evidence-focus"><span className="badge badge-blue">{active.paragraphId}</span><p>“{active.excerpt}”</p></div><div className="source-paragraphs">{source?.paragraphs.map((paragraph) => <section className={paragraph.id === active.paragraphId ? "highlighted" : ""} key={paragraph.id}><small>{paragraph.id}</small><p>{paragraph.text}</p></section>)}</div><footer><button className="btn" onClick={() => setActive(undefined)}>Back to consolidated view</button></footer></aside></div>}
  </>;
}

function AnalysisScreen() {
  const router = useRouter(); const { state, busy, generateQuestions, runAnalysis } = useWorkspace(); const analysis = state.analysis; const [tab, setTab] = useState<"consolidated"|"contributions"|"open">("consolidated");
  if (!analysis) return <EmptyStep title="No analysis yet" copy="Run the multi-source analysis to build a cited consolidated view." action="Analyze sources" onClick={runAnalysis}/>;
  const generate = async () => { await generateQuestions(); router.push("/projects/demo/questions"); };
  const unknowns = analysis.findings.filter((finding) => finding.category === "unknown" || finding.category === "assumption");
  return <><PageHeader eyebrow="Step 2 · Consolidation" title="What the evidence says, and what it does not" copy="Compatible requirements are merged. Provenance stays attached, and inconsistencies appear only when claims cannot coexist." action={<button className="btn btn-primary" disabled={!!busy} onClick={generate}><MessageSquareText size={17}/> Generate questions</button>}/><AIStatus/><ErrorBanner/>
    <div className="card" style={{ display: "grid", gridTemplateColumns: "150px 1fr", gap: 22, padding: 20, marginBottom: 18 }}><div><div className="mono" style={{ fontSize: 36, fontWeight: 800, color: "var(--green)" }}>{analysis.coverageScore}%</div><span className="muted" style={{ fontSize: 12 }}>evidence coverage</span></div><div><strong>Consolidated executive summary</strong><p style={{ margin: "8px 0 0", lineHeight: 1.65 }}>{analysis.executiveSummary}</p></div></div>
    <div style={{ display: "flex", gap: 6, marginBottom: 14 }}>{([ ["consolidated","Consolidated view"], ["contributions","Source contributions"], ["open","Open points"] ] as const).map(([id,label]) => <button key={id} className={`btn btn-sm ${tab === id ? "btn-primary" : ""}`} onClick={() => setTab(id)}>{label}</button>)}</div>
    {tab === "consolidated" && <div className="finding-grid">{analysis.findings.filter((finding) => finding.category !== "unknown").map((finding) => { const sourceCount = new Set(finding.citations.map((citation) => citation.sourceId)).size; return <article className="card finding-card" key={finding.id}><div className="finding-meta"><span className="badge badge-muted">{finding.category}</span><span className="muted mono">{Math.round(finding.confidence * 100)}% confidence</span></div><p>{finding.statement}</p><div className="confirmation-line"><span>{sourceCount} source{sourceCount === 1 ? "" : "s"} supporting this finding</span></div><CitationChips citations={finding.citations}/></article>; })}</div>}
    {tab === "contributions" && <div className="contribution-list">{analysis.sourceContributions.map((item, index) => <article className="card contribution-card" style={{ animationDelay: `${index * 45}ms` }} key={item.id}><div><span className="badge badge-blue">{item.sourceId.replace("SRC-0", "Source ")}</span><span className={`relation relation-${item.relation}`}>{item.relation}</span></div><div><strong>{item.topic}</strong><p>{item.contribution}</p><CitationChips citations={item.citations}/></div></article>)}</div>}
    {tab === "open" && <div style={{ display: "grid", gap: 10 }}>{unknowns.map((finding) => <article className="card" style={{ padding: 17 }} key={finding.id}><span className="badge badge-amber">Needs clarification</span><p style={{ marginBottom: 0 }}>{finding.statement}</p><CitationChips citations={finding.citations}/></article>)}{analysis.inconsistencies.length === 0 && <div className="consistency-note"><Check size={16}/><span><strong>No unresolved inconsistencies were found across the current sources.</strong><small>Complementary evidence was consolidated without manufacturing conflict.</small></span></div>}</div>}
  </>;
}

function QuestionsScreen() {
  const router = useRouter(); const { state, busy, generateQuestions, respond, setQuestionStatus, buildScope } = useWorkspace();
  const [answers, setAnswers] = useState<Record<string,string>>({ "Q-01": "Keep wait-list promotion manual for launch. When an offer expires, notify the coordinator and release capacity only after their confirmation." });
  const [filter, setFilter] = useState<"all" | Question["priority"]>("all");
  if (!state.questions.length) return <EmptyStep title="No clarification questions yet" copy="Generate the smallest useful question set from the cited open points." action="Generate questions" onClick={generateQuestions}/>;
  const build = async () => { await buildScope(); router.push("/projects/demo/estimate"); };
  const answered = state.questions.filter((q) => q.status !== "open").length;
  const visible = filter === "all" ? state.questions : state.questions.filter((question) => question.priority === filter);
  const impact: Record<string, string[]> = { "Q-01": ["Review, offers & wait-list", "Email notifications"], "Q-02": ["Cohort operations"], "Q-03": ["French localization"], "Q-04": ["Email notifications"] };
  return <><PageHeader eyebrow="Step 3 · Human decisions" title="Resolve what matters before estimating" copy="Answers become traceable decisions. Defer or ignore details that should not block the estimate." action={<button className="btn btn-primary" disabled={!!busy || !state.decisions.length} onClick={build}>Build the scope <ArrowRight size={17}/></button>}/><AIStatus/><ErrorBanner/>
    <div className="decision-toolbar card"><div><strong>{answered} of {state.questions.length} questions handled</strong><span>{state.questions.filter((q) => q.priority === "blocking" && q.status === "open").length} blocking decisions remain</span></div><div className="progress-track"><i style={{ width: `${answered / state.questions.length * 100}%` }}/></div><div className="filter-group" aria-label="Filter questions">{(["all", "blocking", "framing", "optional"] as const).map((item) => <button aria-pressed={filter === item} className={`btn btn-sm ${filter === item ? "btn-primary" : ""}`} key={item} onClick={() => setFilter(item)}>{item}</button>)}</div></div>
    <div className="question-list">{visible.map((question) => <article className={`card question-card priority-${question.priority} ${question.status !== "open" ? "resolved" : ""}`} key={question.id}>
      <div style={{ display: "flex", justifyContent: "space-between", gap: 12 }}><span className={`badge ${question.priority === "blocking" ? "badge-red" : question.priority === "framing" ? "badge-amber" : "badge-blue"}`}>{question.priority}</span><span className="badge badge-muted">{question.status}</span></div><h2 style={{ fontSize: 19, margin: "14px 0 7px" }}>{question.text}</h2><p className="muted" style={{ margin: "0 0 6px", fontSize: 14 }}>{question.rationale}</p><p style={{ margin: 0, fontSize: 13 }}><strong>Estimate impact:</strong> {question.estimationImpact}</p><CitationChips citations={question.citations}/>
      <div className="impact-preview"><span>Potential scope impact</span>{impact[question.id]?.map((module) => <span className="badge badge-muted" key={module}>{module}</span>)}</div>
      {question.status === "open" && <div className="answer-panel"><div className="quick-answers"><span>Quick answers</span><button onClick={() => setAnswers({ ...answers, [question.id]: "Keep this manual for launch and record the action in the audit history." })}>Manual for launch</button><button onClick={() => setAnswers({ ...answers, [question.id]: "Include the automated workflow in the initial release." })}>Include in launch</button><button onClick={() => setAnswers({ ...answers, [question.id]: "Move this capability to a separately priced option." })}>Move to options</button></div><label htmlFor={`answer-${question.id}`}>Decision / answer</label><textarea id={`answer-${question.id}`} rows={3} value={answers[question.id] ?? ""} onChange={(event) => setAnswers({ ...answers, [question.id]: event.target.value })}/><div className="answer-actions"><button className="btn btn-success btn-sm" disabled={!answers[question.id]?.trim()} onClick={() => respond(question.id, answers[question.id] ?? "")}><Check size={14}/> Record decision</button><button className="btn btn-sm" onClick={() => setQuestionStatus(question.id, "deferred")}>Defer to framing</button><button className="btn btn-ghost btn-sm" onClick={() => setQuestionStatus(question.id, "ignored")}>Not relevant</button></div></div>}
      {question.answer && <div className="recorded-decision"><Check size={17}/><div><strong>Decision recorded</strong><p>{question.answer}</p><small>Scope impact will be reconciled when you build the scope.</small></div></div>}
    </article>)}</div>
    {state.decisions.length > 0 && <section className="card decision-history"><div><span className="eyebrow">Decision history</span><h2>{state.decisions.length} traceable decision{state.decisions.length === 1 ? "" : "s"}</h2></div>{state.decisions.slice().reverse().map((decision) => <div className="history-row" key={decision.id}><span className="badge badge-green">Recorded</span><p>{decision.statement}</p><time>{new Date(decision.createdAt).toLocaleTimeString([], { hour: "2-digit", minute: "2-digit" })}</time></div>)}</section>}
  </>;
}

function EmptyStep({ title, copy, action, onClick }: { title: string; copy: string; action: string; onClick: () => void | Promise<void> }) {
  return <div className="card" style={{ maxWidth: 650, margin: "80px auto", padding: 42, textAlign: "center" }}><Sparkles size={30} color="#2f6b9a"/><h1 style={{ margin: "18px 0 8px" }}>{title}</h1><p className="muted" style={{ lineHeight: 1.55 }}>{copy}</p><button className="btn btn-primary" style={{ marginTop: 14 }} onClick={onClick}>{action}</button></div>;
}

function EstimateScreen() {
  const router = useRouter(); const { state, busy, buildScope, generateEstimate, changeModuleStatus, editEstimate, setContingency, reviewLine, resolveProposal } = useWorkspace();
  const [selectedId, setSelectedId] = useState<string>();
  const [search, setSearch] = useState("");
  const [statusFilter, setStatusFilter] = useState<"all" | ScopeModule["status"]>("all");
  const [collapsed, setCollapsed] = useState<Set<string>>(new Set());
  const [assistantInsight, setAssistantInsight] = useState<string>();
  if (!state.workstreams.length) return <EmptyStep title="Scope not built yet" copy="Build workstreams and modules from the consolidated analysis and recorded decisions." action="Build the scope" onClick={buildScope}/>;
  if (!state.estimateLines.length) return <><PageHeader eyebrow="Step 4 · Scope" title="A consolidated, cited project scope" copy="Review inclusions, options and exclusions before generating effort ranges." action={<button className="btn btn-primary" disabled={!!busy} onClick={generateEstimate}><Sparkles size={17}/> Generate estimate</button>}/><ScopeCards workstreams={state.workstreams} changeStatus={changeModuleStatus}/></>;
  const modules = state.workstreams.flatMap((w) => w.modules); const moduleMap = new Map(modules.map((m) => [m.id, m])); const totals = calculateTotals(state.estimateLines, modules, state.project.contingencyRate); const selected = state.estimateLines.find((line) => line.id === selectedId) ?? state.estimateLines.find((line) => moduleMap.get(line.moduleId)?.status === "included"); const proposal = state.changeProposal?.status === "pending" ? state.changeProposal : undefined;
  const visibleWorkstreams = state.workstreams.map((workstream) => ({ ...workstream, modules: workstream.modules.filter((module) => (statusFilter === "all" || module.status === statusFilter) && `${module.name} ${module.description} ${module.features.join(" ")}`.toLowerCase().includes(search.toLowerCase())) })).filter((workstream) => workstream.modules.length);
  const selectedModule = selected ? moduleMap.get(selected.moduleId) : undefined;
  return <><PageHeader eyebrow="Step 4 · Deterministic estimate" title="Scope & estimate" copy="Edit effort ranges directly. Exclusions never count, options stay separate, and reserve totals are calculated outside the model." action={<button className="btn" onClick={() => router.push("/projects/demo/preview")}>Preview proposal <ArrowRight size={17}/></button>}/><AIStatus/><ErrorBanner/>
    <div className="estimate-toolbar card"><label><span>Search modules</span><input type="search" placeholder="Search scope…" value={search} onChange={(event) => setSearch(event.target.value)}/></label><div className="filter-group" aria-label="Filter estimate lines">{(["all", "included", "optional", "excluded", "deferred"] as const).map((item) => <button className={`btn btn-sm ${statusFilter === item ? "btn-primary" : ""}`} aria-pressed={statusFilter === item} key={item} onClick={() => setStatusFilter(item)}>{item}</button>)}</div><div className="estimate-count"><strong>{modules.length}</strong><span>modules</span></div></div>
    <div className="estimate-layout"><div className="card estimate-table-wrap"><table className="estimate-table"><thead><tr>{["Module","Status","Low","Likely","High","Risk",""].map((h) => <th key={h}>{h}</th>)}</tr></thead><tbody>{visibleWorkstreams.map((ws) => <TableWorkstream key={ws.id} workstream={ws} lines={state.estimateLines} selectedId={selected?.id} select={(id) => { setSelectedId(id); setAssistantInsight(undefined); }} changeStatus={changeModuleStatus} edit={editEstimate} collapsed={collapsed.has(ws.id)} toggle={() => setCollapsed((current) => { const next = new Set(current); if (next.has(ws.id)) next.delete(ws.id); else next.add(ws.id); return next; })}/>)}</tbody></table>{!visibleWorkstreams.length && <div className="table-empty">No modules match the current filters.</div>}</div>
    <aside className="card copilot-panel"><div className="copilot-title"><span className="eyebrow">Contextual copilot</span><span className="badge badge-muted">Human controlled</span></div>{selected ? <><h2>{selectedModule?.name}</h2><div className="line-signals"><span className={`badge badge-${selected.risk === "high" ? "red" : selected.risk === "medium" ? "amber" : "green"}`}>{selected.risk} risk</span><span className="badge badge-muted">{selected.confidence} confidence</span>{selected.manualOverride && <span className="badge badge-blue">manual override</span>}</div><CitationChips citations={selectedModule?.citations ?? []}/><p className="copilot-rationale">{selected.rationale}</p><div className="copilot-actions"><button onClick={() => setAssistantInsight(`This line covers ${selectedModule?.features.join(", ")}. Its range is driven by ${selected.rationale.toLowerCase()}`)}>Explain this line</button><button onClick={() => setAssistantInsight(`${selectedModule?.dependencies.length ? `Dependencies: ${selectedModule.dependencies.join(", ")}. ` : "No upstream module dependency is recorded. "}${selectedModule?.assumptions.join(" ") || "No explicit assumption is recorded."}`)}>Find missing work</button><button onClick={() => setAssistantInsight(`${selectedModule?.citations.length ?? 0} source reference${selectedModule?.citations.length === 1 ? "" : "s"} currently support this module. Open a citation to inspect the original paragraph.`)}>Compare with source evidence</button><button onClick={() => setAssistantInsight(`Client wording: ${selectedModule?.description}`)}>Rewrite for the client</button></div>{assistantInsight && <div className="workspace-insight"><span>Workspace insight</span><p>{assistantInsight}</p></div>}<button className="btn btn-primary challenge-button" disabled={!!busy} onClick={() => reviewLine(selected)}><GitCompare size={16}/> Challenge this estimate</button></> : <p className="muted">Select an estimate line to inspect its evidence, risk and assumptions.</p>}
      {proposal && <div className="proposal-diff"><div className="diff-heading"><span className="badge badge-blue">AI change proposal</span><small>Nothing changes until accepted</small></div><p>{proposal.explanation}</p><Diff before={proposal.before} after={proposal.after}/><div className="diff-actions"><button className="btn btn-success btn-sm" onClick={() => resolveProposal(true)}><Check size={14}/> Accept change</button><button className="btn btn-danger btn-sm" onClick={() => resolveProposal(false)}><X size={14}/> Reject</button></div></div>}
    </aside></div>
    <div className="totals-dock card mono"><Total label="Base low" value={totals.base.low}/><Total label="Base likely" value={totals.base.likely}/><Total label="Base high" value={totals.base.high}/><label>Reserve<select aria-label="Estimate reserve" value={state.project.contingencyRate} onChange={(e) => setContingency(Number(e.target.value))}><option value={0.1}>10%</option><option value={0.15}>15%</option><option value={0.2}>20%</option></select></label><Total label="Proposed likely" value={totals.proposed.likely} accent/><div className="option-total"><span>Options</span><strong>{totals.options.low} / {totals.options.likely} / {totals.options.high} d</strong></div></div>
  </>;
}

function ScopeCards({ workstreams, changeStatus }: { workstreams: ReturnType<typeof useWorkspace>["state"]["workstreams"]; changeStatus: ReturnType<typeof useWorkspace>["changeModuleStatus"] }) { return <div style={{ display: "grid", gap: 14 }}>{workstreams.map((ws) => <section className="card" style={{ padding: 18 }} key={ws.id}><h2 style={{ margin: 0, fontSize: 19 }}>{ws.name}</h2><p className="muted" style={{ marginTop: 6 }}>{ws.description}</p><div style={{ display: "grid", gap: 8 }}>{ws.modules.map((module) => <div key={module.id} style={{ display: "grid", gridTemplateColumns: "1fr 130px", gap: 14, padding: 12, border: "1px solid var(--border)", borderRadius: 7 }}><div><strong>{module.name}</strong><div className="muted" style={{ marginTop: 4, fontSize: 13 }}>{module.features.join(", ")}</div><CitationChips citations={module.citations}/></div><StatusSelect value={module.status} onChange={(value) => changeStatus(module.id, value)}/></div>)}</div></section>)}</div>; }

function TableWorkstream({ workstream, lines, selectedId, select, changeStatus, edit, collapsed, toggle }: { workstream: ReturnType<typeof useWorkspace>["state"]["workstreams"][number]; lines: EstimateLine[]; selectedId?: string; select: (id: string) => void; changeStatus: ReturnType<typeof useWorkspace>["changeModuleStatus"]; edit: ReturnType<typeof useWorkspace>["editEstimate"]; collapsed: boolean; toggle: () => void }) { return <><tr className="workstream-row"><th colSpan={7}><button type="button" aria-expanded={!collapsed} onClick={toggle}>{collapsed ? <ChevronRight size={16}/> : <ChevronDown size={16}/>}<span>{workstream.name}</span><small>{workstream.modules.length} modules</small></button></th></tr>{!collapsed && workstream.modules.map((module) => { const line = lines.find((item) => item.moduleId === module.id); if (!line) return null; return <tr key={module.id} className={selectedId === line.id ? "selected" : ""} onClick={() => select(line.id)}><td><strong>{module.name}</strong>{line.manualOverride && <span className="edited-mark" title="Manually edited">edited</span>}<small>{module.description}</small></td><td><StatusSelect value={module.status} onChange={(value) => changeStatus(module.id, value)}/></td>{(["low","likely","high"] as const).map((key) => <td key={key}><input aria-label={`${module.name} ${key}`} type="number" min="0" step="0.5" value={line[key]} onClick={(event) => event.stopPropagation()} onChange={(event) => edit(line.id, { [key]: Number(event.target.value) })}/></td>)}<td><span className={`badge ${line.risk === "high" ? "badge-red" : line.risk === "medium" ? "badge-amber" : "badge-green"}`}>{line.risk}</span></td><td><button className="btn btn-ghost btn-sm" aria-label={`Review ${module.name}`} onClick={(event) => { event.stopPropagation(); select(line.id); }}><ChevronRight size={15}/></button></td></tr>; })}</>; }

function StatusSelect({ value, onChange }: { value: ScopeModule["status"]; onChange: (value: ScopeModule["status"]) => void }) { return <select aria-label="Module status" value={value} onClick={(e) => e.stopPropagation()} onChange={(e) => onChange(e.target.value as ScopeModule["status"])} style={{ width: "100%", padding: 7, color: value === "included" ? "var(--green)" : value === "optional" ? "var(--amber)" : "var(--muted)", border: "1px solid var(--border)", borderRadius: 6, background: "white", fontSize: 12, fontWeight: 750 }}><option value="included">Included</option><option value="optional">Optional</option><option value="excluded">Excluded</option><option value="deferred">Deferred</option></select>; }
function Diff({ before, after }: { before: EstimateLine; after: EstimateLine }) { return <div className="diff-grid mono"><div className="diff-before"><span>Before</span><strong>{before.low} / {before.likely} / {before.high} d</strong><small>{before.rationale}</small></div><div className="diff-after"><span>After</span><strong>{after.low} / {after.likely} / {after.high} d</strong><small>{after.rationale}</small></div></div>; }
function Total({ label, value, accent }: { label: string; value: number; accent?: boolean }) { return <div><div className="muted" style={{ fontSize: 12 }}>{label}</div><strong style={{ display: "block", marginTop: 5, fontSize: 22, color: accent ? "var(--blue)" : undefined }}>{value.toFixed(1)} d</strong></div>; }

function PreviewScreen() {
  const { state } = useWorkspace(); const [mode, setMode] = useState<"internal"|"client">("client"); const modules = state.workstreams.flatMap((w) => w.modules); const totals = useMemo(() => calculateTotals(state.estimateLines, modules, state.project.contingencyRate), [state.estimateLines, modules, state.project.contingencyRate]);
  if (!state.estimateLines.length) return <EmptyStep title="No proposal yet" copy="Generate the scope and estimate before opening the proposal." action="Go to scope" onClick={() => location.assign("/projects/demo/estimate")}/>;
  const optional = modules.filter((module) => module.status === "optional");
  const excluded = modules.filter((module) => module.status === "excluded");
  const exportCsv = () => { const escape = (value: string | number | boolean) => `"${String(value).replaceAll('"', '""')}"`; const header = ["Workstream", "Module", "Status", "Low", "Likely", "High", "Risk", "Confidence", "Manual override", "Source references"]; const rows = state.workstreams.flatMap((workstream) => workstream.modules.map((module) => { const line = state.estimateLines.find((item) => item.moduleId === module.id); return [workstream.name, module.name, module.status, line?.low ?? 0, line?.likely ?? 0, line?.high ?? 0, line?.risk ?? "", line?.confidence ?? "", line?.manualOverride ?? false, module.citations.map((citation) => citation.paragraphId).join(" | ")]; })); const blob = new Blob(["\ufeff", [header, ...rows].map((row) => row.map(escape).join(",")).join("\n")], { type: "text/csv;charset=utf-8" }); const url = URL.createObjectURL(blob); const link = document.createElement("a"); link.href = url; link.download = "scopeforge-morrow-ridge-estimate.csv"; link.click(); URL.revokeObjectURL(url); };
  return <><PageHeader eyebrow="Step 5 · Proposal" title="One estimate, two safe views" copy="Switching views changes the data projection, not just the styling. Client mode never includes internal rationale, risk, confidence or reserve detail." action={<div className="preview-actions no-print"><div className="view-switch" aria-label="Proposal view"><button aria-pressed={mode === "internal"} onClick={() => setMode("internal")}>Internal</button><button aria-pressed={mode === "client"} onClick={() => setMode("client")}>Client-ready</button><i className={mode}/></div>{mode === "internal" && <button className="btn" onClick={exportCsv}><Download size={16}/> Estimate CSV</button>}<button className="btn" onClick={() => window.print()}><Printer size={16}/> Print / PDF</button></div>}/>
    <div className={`view-safety no-print ${mode}`}><ShieldCheck size={16}/><span>{mode === "client" ? "Client-safe projection active. Internal notes and commercial mechanics are excluded." : "Internal working view. Risks, confidence, citations and reserve mechanics are visible."}</span></div>
    <article className={`card proposal-document proposal-${mode}`}><header className="proposal-cover"><div><div className="eyebrow">Project proposal · Fictional demo</div><h1>{state.project.name}</h1><p>Prepared with ScopeForge · {new Date().toLocaleDateString("en-GB")}</p></div><span className="brand-mark">S</span></header>
      <section className="proposal-intro"><span className="proposal-section-number">01</span><div><h2>Context and objectives</h2><p>{state.analysis?.executiveSummary}</p><div className="objective-grid"><div><strong>Outcome</strong><span>A trusted path from retreat discovery to confirmed place.</span></div><div><strong>Launch shape</strong><span>Responsive web platform for six initial retreats.</span></div><div><strong>Operating model</strong><span>Coordinator-reviewed applications with online deposits.</span></div></div></div></section>
      <section className="proposal-scope"><span className="proposal-section-number">02</span><div><h2>Included scope</h2>{state.workstreams.map((workstream) => <div className="proposal-workstream" key={workstream.id}><h3>{workstream.name}</h3>{workstream.modules.filter((module) => module.status === "included").map((module) => { const line = state.estimateLines.find((item) => item.moduleId === module.id); return <div className="proposal-module" key={module.id}><div><strong>{module.name}</strong><p>{module.description}</p>{mode === "internal" && <div className="internal-signals"><span className={`badge badge-${line?.risk === "high" ? "red" : line?.risk === "medium" ? "amber" : "green"}`}>{line?.risk} risk</span><span className="badge badge-muted">{line?.confidence} confidence</span><CitationChips citations={module.citations}/></div>}</div><span className="mono">{line?.low}-{line?.high} days</span></div>})}</div>)}</div></section>
      <section className="proposal-effort"><span><small>Indicative delivery effort</small><strong className="mono">{totals.proposed.low.toFixed(1)}-{totals.proposed.high.toFixed(1)} days</strong></span><span><small>Likely planning case</small><strong className="mono">{totals.proposed.likely.toFixed(1)} days</strong></span><span><small>Indicative calendar</small><strong>10-14 weeks</strong></span>{mode === "internal" && <div className="internal-math">Internal base {totals.base.likely} d + reserve {totals.reserve.likely} d ({state.project.contingencyRate * 100}%)</div>}</section>
      <section className="proposal-columns"><div><span className="proposal-section-number">03</span><h2>Options</h2>{optional.map((module) => { const line = state.estimateLines.find((item) => item.moduleId === module.id); return <div className="proposal-option" key={module.id}><strong>{module.name}</strong><span className="mono">{line?.low}-{line?.high} days</span><p>{module.description}</p></div>})}</div><div><span className="proposal-section-number">04</span><h2>Exclusions</h2><ul>{excluded.map((module) => <li key={module.id}>{module.name}</li>)}</ul><h2>Working assumptions</h2><ul><li>Client content and photography arrive progressively.</li><li>Wait-list promotion remains manual for launch.</li><li>Refund decisions remain an operations process.</li></ul></div></section>
      {mode === "internal" && <section className="internal-appendix"><div><span className="proposal-section-number">05</span><h2>Internal decision record</h2></div>{state.decisions.map((decision) => <div key={decision.id}><span className="badge badge-green">Decision</span><p>{decision.statement}</p></div>)}<h3>Recent workspace activity</h3>{state.activity.slice(-4).reverse().map((item) => <p className="activity-line" key={item.id}>{item.label}<time>{new Date(item.createdAt).toLocaleTimeString([], { hour: "2-digit", minute: "2-digit" })}</time></p>)}</section>}
      <footer>This proposal is based on the fictional evidence and decisions recorded in ScopeForge. Final delivery planning follows technical discovery.</footer>
    </article>
  </>;
}
